# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLK]
	#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {Temp[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[0]}]
set_property PACKAGE_PIN V16 [get_ports {Temp[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[1]}]
set_property PACKAGE_PIN W16 [get_ports {Temp[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[2]}]
set_property PACKAGE_PIN W17 [get_ports {Temp[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[3]}]
set_property PACKAGE_PIN W15 [get_ports {Temp[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[4]}]
set_property PACKAGE_PIN V15 [get_ports {Temp[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[5]}]
set_property PACKAGE_PIN W14 [get_ports {Temp[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[6]}]
set_property PACKAGE_PIN W13 [get_ports {Temp[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[7]}]
set_property PACKAGE_PIN V2 [get_ports {Temp[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[8]}]
set_property PACKAGE_PIN T3 [get_ports {Temp[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[9]}]
set_property PACKAGE_PIN T2 [get_ports {Temp[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[10]}]
set_property PACKAGE_PIN R3 [get_ports {Temp[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Temp[11]}]
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {Cat[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Cat[0]}]
set_property PACKAGE_PIN W6 [get_ports {Cat[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Cat[1]}]
set_property PACKAGE_PIN U8 [get_ports {Cat[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Cat[2]}]
set_property PACKAGE_PIN V8 [get_ports {Cat[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Cat[3]}]
set_property PACKAGE_PIN U5 [get_ports {Cat[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Cat[4]}]
set_property PACKAGE_PIN V5 [get_ports {Cat[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Cat[5]}]
set_property PACKAGE_PIN U7 [get_ports {Cat[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Cat[6]}]


set_property PACKAGE_PIN U2 [get_ports {An[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[0]}]
set_property PACKAGE_PIN U4 [get_ports {An[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[1]}]
set_property PACKAGE_PIN V4 [get_ports {An[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[2]}]
set_property PACKAGE_PIN W4 [get_ports {An[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {An[3]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {Leds[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {Leds[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {Leds[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {Leds[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {Leds[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Leds[4]}]

#Buttons
set_property PACKAGE_PIN U18 [get_ports {Confirm}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Confirm}]
set_property PACKAGE_PIN T18 [get_ports {Inc}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Inc}]
set_property PACKAGE_PIN W19 [get_ports {Start}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Start}]
set_property PACKAGE_PIN U17 [get_ports {Dec}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {Dec}]